package dev.allstak.spring;

import dev.allstak.AllStak;
import dev.allstak.AllStakClient;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.core.Appender;
import org.apache.logging.log4j.core.Core;
import org.apache.logging.log4j.core.Filter;
import org.apache.logging.log4j.core.LogEvent;
import org.apache.logging.log4j.core.appender.AbstractAppender;
import org.apache.logging.log4j.core.config.Property;
import org.apache.logging.log4j.core.config.plugins.Plugin;
import org.apache.logging.log4j.core.config.plugins.PluginAttribute;
import org.apache.logging.log4j.core.config.plugins.PluginElement;
import org.apache.logging.log4j.core.config.plugins.PluginFactory;

import java.util.Map;

/**
 * Log4j2 appender that forwards log events to AllStak.
 *
 * <p>This is the Log4j2 counterpart of {@link AllStakLogbackAppender} and is
 * intentionally behavior-identical: every event at or above the configured
 * {@code threshold} is routed through {@link AllStakClient#captureLog}, which
 * itself promotes {@code warn}/{@code error}/{@code fatal} entries to
 * breadcrumbs when auto-breadcrumbs are enabled. Throwable stacks are folded
 * into the message exactly as the Logback appender does.
 *
 * <p>It can be wired declaratively in {@code log4j2.xml}:
 * <pre>{@code
 * <Configuration packages="dev.allstak.spring">
 *   <Appenders>
 *     <AllStak name="allstak" threshold="TRACE"/>
 *   </Appenders>
 *   <Loggers>
 *     <Root level="INFO">
 *       <AppenderRef ref="allstak"/>
 *     </Root>
 *   </Loggers>
 * </Configuration>
 * }</pre>
 *
 * or programmatically by {@link AllStakAutoConfiguration} when Log4j2 is the
 * active logging backend (see {@link #create}).
 */
@Plugin(name = "AllStak", category = Core.CATEGORY_NAME, elementType = Appender.ELEMENT_TYPE, printObject = true)
public final class AllStakLog4j2Appender extends AbstractAppender {

    private static final ThreadLocal<Boolean> SENDING = ThreadLocal.withInitial(() -> false);

    /** Default capture threshold. Matches the Logback appender, which captures every level. */
    private static final Level DEFAULT_THRESHOLD = Level.TRACE;

    private final Level threshold;

    AllStakLog4j2Appender(String name, Filter filter, Level threshold) {
        super(name, filter, null, true, Property.EMPTY_ARRAY);
        this.threshold = threshold != null ? threshold : DEFAULT_THRESHOLD;
    }

    /**
     * Log4j2 plugin factory — invoked by the {@code <AllStak/>} element in
     * {@code log4j2.xml}.
     */
    @PluginFactory
    public static AllStakLog4j2Appender createPlugin(
            @PluginAttribute("name") String name,
            @PluginAttribute("threshold") String threshold,
            @PluginElement("Filter") Filter filter) {
        String appenderName = (name == null || name.isBlank()) ? "allstak" : name;
        Level level = threshold == null ? DEFAULT_THRESHOLD : Level.toLevel(threshold, DEFAULT_THRESHOLD);
        return new AllStakLog4j2Appender(appenderName, filter, level);
    }

    /**
     * Programmatic factory used by {@link AllStakAutoConfiguration} when it
     * registers the appender on the running Log4j2 context.
     */
    public static AllStakLog4j2Appender create(String name) {
        return new AllStakLog4j2Appender(name, null, DEFAULT_THRESHOLD);
    }

    @Override
    public void append(LogEvent event) {
        // Prevent infinite loop: don't capture logs generated by the AllStak SDK itself.
        if (SENDING.get()) return;

        Level eventLevel = event.getLevel();
        if (eventLevel == null || !eventLevel.isMoreSpecificThan(threshold)) {
            // Below the configured threshold — drop. (isMoreSpecificThan is
            // inclusive of equal levels, so threshold itself is captured.)
            return;
        }

        String loggerName = event.getLoggerName();
        if (loggerName != null && (loggerName.startsWith("dev.allstak") || loggerName.contains("AllStak"))) {
            return;
        }

        AllStakClient client = AllStak.getClient();
        if (client == null) return;

        SENDING.set(true);
        try {
            String level = mapLevel(eventLevel);
            String formatted = event.getMessage() != null ? event.getMessage().getFormattedMessage() : "";

            // Skip SDK internal debug messages.
            if (formatted != null && formatted.startsWith("[AllStak SDK")) return;

            Throwable thrown = event.getThrown();

            Map<String, String> contextData = event.getContextData() != null
                    ? event.getContextData().toMap()
                    : Map.of();

            // Get trace_id from the logging context (MDC), falling back to the
            // active request context on this thread.
            String traceId = contextData.get("traceId");
            if (traceId == null) {
                var reqCtx = AllStakClient.getRequestContext();
                if (reqCtx != null) traceId = reqCtx.getTraceId();
            }

            // Get service from the logging context.
            String service = contextData.get("service");

            Map<String, Object> metadata = null;
            if (!contextData.isEmpty()) {
                metadata = new java.util.HashMap<>(contextData);
                metadata.remove("traceId"); // already a top-level field
                metadata.remove("service");
                if (metadata.isEmpty()) metadata = null;
            }

            // Promote ERROR-with-throwable to a captureException so caught-and-
            // logged exceptions still surface in the Issues view. Mirrors the
            // Logback appender's behavior.
            if (thrown != null && eventLevel.isMoreSpecificThan(Level.ERROR)) {
                Map<String, Object> errMeta = metadata == null ? new java.util.HashMap<>() : new java.util.HashMap<>(metadata);
                if (formatted != null) errMeta.put("log_message", formatted);
                String loggerNameForMeta = event.getLoggerName();
                if (loggerNameForMeta != null) errMeta.put("logger", loggerNameForMeta);
                if (traceId != null) errMeta.put("trace_id", traceId);
                client.captureException(thrown, "error", errMeta);
            }

            // Fold the throwable + stack into the log message for readability.
            String message = formatted == null ? "" : formatted;
            if (thrown != null) {
                StringBuilder sb = new StringBuilder(message);
                sb.append("\n").append(thrown.getClass().getName())
                  .append(": ").append(thrown.getMessage());
                for (StackTraceElement step : thrown.getStackTrace()) {
                    sb.append("\n  at ").append(step.toString());
                    if (sb.length() > 4000) break;
                }
                message = sb.toString();
            }

            client.captureLog(level, message, service, traceId, null, null, null, null, null, metadata);
        } catch (Exception e) {
            // Never break the host application.
        } finally {
            SENDING.set(false);
        }
    }

    private String mapLevel(Level level) {
        String name = level.name().toUpperCase();
        return switch (name) {
            case "TRACE", "ALL" -> "debug";
            case "DEBUG" -> "debug";
            case "INFO" -> "info";
            case "WARN" -> "warn";
            case "ERROR" -> "error";
            case "FATAL" -> "error";
            default -> "info";
        };
    }
}
