package dev.allstak.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import java.util.UUID;

/**
 * Generates an {@code allstak-debug-meta.properties} resource so the
 * runtime SDK can attach a stable debug id to captured events. The id
 * ties a JAR-on-disk to the source bundle uploaded by the
 * {@link UploadSourceBundleMojo} goal.
 */
@Mojo(name = "generate-debug-id", defaultPhase = LifecyclePhase.GENERATE_RESOURCES, threadSafe = true)
public final class GenerateDebugIdMojo extends AbstractMojo {

    /** Where to write the resource. Defaults to {@code target/generated-resources/allstak}. */
    @Parameter(defaultValue = "${project.build.directory}/generated-resources/allstak", required = true)
    private Path outputDirectory;

    /**
     * Reuse an existing debug id rather than minting a fresh one. Useful in
     * release pipelines that pre-allocate the id so the bundle upload can
     * run independently of the build.
     */
    @Parameter
    private String debugId;

    @Override
    public void execute() throws MojoExecutionException {
        try {
            Files.createDirectories(outputDirectory);
            String id = (debugId == null || debugId.isBlank())
                    ? UUID.randomUUID().toString()
                    : debugId.trim();
            Properties p = new Properties();
            p.setProperty("debug.id", id);
            Path file = outputDirectory.resolve("allstak-debug-meta.properties");
            try (OutputStream os = Files.newOutputStream(file)) {
                p.store(os, "AllStak debug-meta — generated by allstak-maven-plugin");
            }
            getLog().info("AllStak debug id " + id + " written to " + file);
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to write allstak-debug-meta.properties", e);
        }
    }
}
