package dev.allstak.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

import java.io.IOException;
import java.io.OutputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.UUID;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Bundles every {@code .java} file under the project's source roots into a
 * zip and uploads it to AllStak so the dashboard can resolve symbolicated
 * stack frames to readable source context lines. The companion
 * {@link GenerateDebugIdMojo} writes the matching debug id into the JAR.
 */
@Mojo(name = "upload-source-bundle", defaultPhase = LifecyclePhase.PACKAGE, threadSafe = true)
public final class UploadSourceBundleMojo extends AbstractMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /** Endpoint that accepts a multipart upload — typically the platform's source-map upload route. */
    @Parameter(property = "allstak.upload.url", defaultValue = "https://api.allstak.sa/api/v1/admin/source-bundles")
    private String uploadUrl;

    /** API key (project-scoped) used as {@code X-AllStak-Key}. */
    @Parameter(property = "allstak.api.key", required = true)
    private String apiKey;

    /** Debug id previously generated by {@link GenerateDebugIdMojo}. Override to upload an arbitrary id. */
    @Parameter(property = "allstak.debug.id")
    private String debugId;

    /** Skip the upload — useful for snapshot builds. */
    @Parameter(property = "allstak.upload.skip", defaultValue = "false")
    private boolean skip;

    @Override
    public void execute() throws MojoExecutionException {
        if (skip) { getLog().info("AllStak upload skipped (allstak.upload.skip=true)"); return; }

        String id = debugId;
        if (id == null || id.isBlank()) {
            id = readGeneratedId();
            if (id == null) id = UUID.randomUUID().toString();
        }

        Path tempZip;
        try {
            tempZip = Files.createTempFile("allstak-source-bundle-", ".zip");
            int written;
            try (ZipOutputStream zout = new ZipOutputStream(Files.newOutputStream(tempZip))) {
                written = bundleSources(zout);
            }
            getLog().info("Bundled " + written + " source files, debug id " + id);

            byte[] bytes = Files.readAllBytes(tempZip);
            HttpClient client = HttpClient.newHttpClient();
            HttpRequest req = HttpRequest.newBuilder(URI.create(uploadUrl))
                    .header("X-AllStak-Key", apiKey)
                    .header("X-AllStak-Debug-Id", id)
                    .header("Content-Type", "application/zip")
                    .POST(HttpRequest.BodyPublishers.ofByteArray(bytes))
                    .build();
            HttpResponse<String> resp = client.send(req, HttpResponse.BodyHandlers.ofString());
            if (resp.statusCode() < 200 || resp.statusCode() >= 300) {
                throw new MojoExecutionException("Upload failed: HTTP " + resp.statusCode() + " — " + resp.body());
            }
            getLog().info("AllStak source bundle uploaded: HTTP " + resp.statusCode());
        } catch (IOException | InterruptedException e) {
            throw new MojoExecutionException("Source bundle upload failed", e);
        }
    }

    private int bundleSources(ZipOutputStream zout) throws IOException {
        List<String> roots = project.getCompileSourceRoots();
        int written = 0;
        for (String root : roots) {
            Path rootPath = Path.of(root);
            if (!Files.isDirectory(rootPath)) continue;
            try (var stream = Files.walk(rootPath)) {
                var iter = stream.filter(Files::isRegularFile)
                        .filter(p -> p.toString().endsWith(".java")).iterator();
                while (iter.hasNext()) {
                    Path p = iter.next();
                    String entry = rootPath.relativize(p).toString().replace('\\', '/');
                    zout.putNextEntry(new ZipEntry(entry));
                    Files.copy(p, zout);
                    zout.closeEntry();
                    written++;
                }
            }
        }
        return written;
    }

    private String readGeneratedId() {
        try {
            Path file = Path.of(project.getBuild().getDirectory())
                    .resolve("generated-resources/allstak/allstak-debug-meta.properties");
            if (!Files.isRegularFile(file)) return null;
            for (String line : Files.readAllLines(file)) {
                if (line.startsWith("debug.id=")) return line.substring("debug.id=".length()).trim();
            }
        } catch (IOException ignored) {}
        return null;
    }
}
